
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;

namespace CustomerDatabaseLibraryEntityFramework.Models
{
    public partial class Customer
    {
        public int Identifier { get; set; }
        [Required]
        [Comment("Company name")]
        public string CompanyName { get; set; }
        [Required]
        [Comment("Contact full name")]
        public string ContactName { get; set; }
        [Required]
        [Comment("Contact type key")]
        public int? ContactTypeIdentifier { get; set; }
        [Required]
        [Comment("Gender key")]
        public int? GenderIdentifier { get; set; }

        public virtual ContactTypes ContactTypeIdentifierNavigation { get; set; }
        public virtual Genders GenderIdentifierNavigation { get; set; }

        public override string ToString() => CompanyName;

    }
}