// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CustomerDatabaseLibraryEntityFramework.Models
{
    public partial class Genders
    {
        public Genders()
        {
            Customer = new HashSet<Customer>();
        }

        public int id { get; set; }
        public string GenderType { get; set; }

        public virtual ICollection<Customer> Customer { get; set; }

        public override string ToString() => GenderType;

    }
}