// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CustomerDatabaseLibraryEntityFramework.Data;
using CustomerDatabaseLibraryEntityFramework.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace CustomerDatabaseLibraryEntityFramework.Data.Configurations
{
    public partial class ContactTypesConfiguration : IEntityTypeConfiguration<ContactTypes>
    {
        public void Configure(EntityTypeBuilder<ContactTypes> entity)
        {
            entity.HasKey(e => e.Identifier);

            entity.Property(e => e.ContactType).HasMaxLength(50);
            entity.Property(e => e.ContactType).HasComment("Contact type"); // Karen added

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ContactTypes> entity);
    }
}
