// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CustomerDatabaseLibraryEntityFramework.Data;
using CustomerDatabaseLibraryEntityFramework.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace CustomerDatabaseLibraryEntityFramework.Data.Configurations
{
    public partial class CustomerConfiguration : IEntityTypeConfiguration<Customer>
    {
        public void Configure(EntityTypeBuilder<Customer> entity)
        {
            entity.HasKey(e => e.Identifier)
                .HasName("Customer$PrimaryKey");

            entity.Property(e => e.CompanyName).HasMaxLength(255);

            entity.Property(e => e.ContactName).HasMaxLength(255);

            entity.HasOne(d => d.ContactTypeIdentifierNavigation)
                .WithMany(p => p.Customer)
                .HasForeignKey(d => d.ContactTypeIdentifier)
                .HasConstraintName("FK_Customer_ContactTypes");

            entity.HasOne(d => d.GenderIdentifierNavigation)
                .WithMany(p => p.Customer)
                .HasForeignKey(d => d.GenderIdentifier)
                .HasConstraintName("FK_Customer_Genders");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Customer> entity);
    }
}
