// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace DependencyInjectionSimple.Models;

public partial class Customers
{
    public Customers()
    {
        Orders = new HashSet<Orders>();
    }

    public int Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Address { get; set; }
    public string Phone { get; set; }
    public string Email { get; set; }

    public virtual ICollection<Orders> Orders { get; set; }

    public override string ToString() => $"{Id,-3}{FirstName} {LastName}";

}