// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace DependencyInjectionSimple.Models;

public partial class OrderDetails
{
    public int Id { get; set; }
    public int Quantity { get; set; }
    public int ProductId { get; set; }
    public int OrderId { get; set; }

    public virtual Orders Order { get; set; }
    public virtual Products Product { get; set; }
}