// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace DependencyInjectionSimple.Models;

public partial class Orders
{
    public Orders()
    {
        OrderDetails = new HashSet<OrderDetails>();
    }

    public int Id { get; set; }
    public DateTime OrderPlaced { get; set; }
    public DateTime? OrderFulfilled { get; set; }
    public int CustomerId { get; set; }

    public virtual Customers Customer { get; set; }
    public virtual ICollection<OrderDetails> OrderDetails { get; set; }
}