// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NorthWind2020ConsoleApp.Models
{
    public partial class BusinessEntityPhone
    {
        public int BusinessEntityPhoneId { get; set; }
        public string PhoneNumber { get; set; }
        public int? PhoneNumberTypeId { get; set; }
        public DateTime? ModifiedDate { get; set; }
    }
}